[workspace.package]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["crates/*", "kernel"]

[workspace.dependencies]
spin = "0.9"
volatile = "0.4"
x86_64 = "0.14"
uart_16550 = "0.2"
pc-keyboard = "0.7"
paste = "1.0"          # macro ident concat
bit_field = "0.10"
rustc-demangle = "0.1" # backtrace demangling
# image = "0.24"
# bitvec = "1.0.1"
# tracing = { version = "0.1.37", default-features = false }

# backtrace symbol lookup
[workspace.dependencies.elf]
version = "0.7"
default-features = false

[workspace.dependencies.smallvec]
version = "1.10"
features = ["const_generics"]

#[dependencies.itertools]
#version = "0.10.5"
#default-features = false

[workspace.dependencies.chrono]
version = "0.4"
default-features = false

[workspace.dependencies.crossbeam-queue]
version = "0.3"
default-features = false
features = ["alloc"]

[workspace.dependencies.crossbeam]
version = "0.8"
default-features = false
features = ["alloc"]

[workspace.dependencies.futures-util]
version = "0.3"
default-features = false
features = ["alloc"]

# no_std thiserrror alternative
[workspace.dependencies.snafu]
version = "0.7"
default-features = false
features = ["rust_1_46"]

# backtracing with DWARF
# [dependencies.gimli]
# version = "0.27"
# default-features = false
# features = ["read", "write"]
