[package]
name = "hyperion-driver-qemu"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spin.workspace = true
uart_16550.workspace = true
x86_64.workspace = true
